@startuml
title 主体业务流程图

start
:开始业务操作;
if (发站开单)
    partition 发站开单 {
        :填写客户信息;
        :填写运单信息;
        :填写货物信息;
        :填写费用信息;
        while(开单)
            :客户信息校验;
            :运单信息校验;
            :货物信息校验;
            :费用信息校验;
        endwhile(校验通过)
    }
else if(新建装车合同)
    partition 新建装车合同 {
        :填写线路信息;
        :填写车辆信息;
        :填写结算方式;
        while(新建)
            :线路信息校验;
            :车辆信息校验;
            :结算方式校验;
        endwhile(校验通过)
    }
else if (装车和发车)
    partition 装车和发车 {
        :选择运单;
        while(发车)
            :校验选择运单的发站和到站\n是否符合装车合同的路线;
        endwhile(校验通过)
        :发车;
    }
else if (签收和计算费用)
    partition 签收 {
        while(签收)
            :判断业务是否全部执行完成;
        endwhile(数据校验通过)
        if (计算费用) then (通过)
            :生成费用清单;
        else (异常)
            :人工核对;
        endif
        :展示运单整体操作流程;
        :展示全部费用项;
    }
endif
:业务完成;
stop
@enduml